### ISSUE TITLE
No module named api.v3

### ISSUE THREAD

**Issue by HardlyMirage** [zehengl/ezapi-yelp#1]
I wrote a simple test script and it doesn't appear to find the v3 module:

**Error**

```
root@scrapy:/mnt/leads/extractor# python api/yelp.py
Traceback (most recent call last):
  File "api/yelp.py", line 5, in <module>
    from yelp.api.v3 import Yelp
  File "/mnt/leads/extractor/api/yelp.py", line 5, in <module>
    from yelp.api.v3 import Yelp
ImportError: No module named api.v3
```

**Code**

```
# -*- coding: utf-8 -*-
"""
Yelp data extractor from API
"""
from yelp.api.v3 import Yelp

APP_ID = 'XXX'
APP_SECRET = 'XXX'

YELP = Yelp(APP_ID, APP_SECRET)

print YELP.search(location='metraire', limit=1)
```

**Versions**

Python: 2.7
ezapi-yelp: 0.3.1

**Comment by zehengl** [comment]
Hello,

did you install ezapi-yelp as your one of dependencies? 

Usually it's best practise to use virtual environment to manage your project-wise dependencies. Here's the example how you may do it, based on your test script (see attachment [test.zip](https://github.com/zehengl/ezapi-yelp/files/1099379/test.zip)). 


```
cd test
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
python test.py
```

Here's the ```requirements.txt```
```
ezapi-yelp==0.3.1
``` 

In general, you put what you need for your project in this file.

**Comment by HardlyMirage** [comment]
Yes, I specified that I have ezapi-yelp version 0.3.1 installed in the original post

**Comment by zehengl** [comment]
can you ```pip freeze``` your python environment?

**Comment by zehengl** [comment]
@HardlyMirage forgot to mention, have you tried the steps in my comment and does it work?

**Comment by HardlyMirage** [comment]
@zehengl I'm so very sorry. It was my mistake. I was running the script on my system while my python env is setup in a separate VM.

**Comment by zehengl** [comment]
@HardlyMirage np, drop me a line if you have any suggestion
